export default {
  ok: 'OK',
  cancel: 'Cancel',
  companies: 'Companies',
  settings: 'Settings',
  serverList: 'Server List',
  login: 'Login',
  emailAddress: 'E-mail',
  password: 'Password',
  loginButton: 'Log In',
  loading: 'Loading',
  createServer: 'Create Server',
  addressServer: 'Server address',
  create: 'Create',
  appSettings: 'App Settings',
  Profile: 'Profile',
  Warehouse: 'Warehouse',
  ChooseWarehouse: 'Choose Warehouse',
  ToCompanyList: 'To company list',
  Exit: 'Exit',
  Shipment: 'Shipment',
  Main: 'Main',
  LastDocuments: 'Last documents',
  Items: 'Items',
  MrkCodes: 'Marking Codes',
  IssueOrders: 'Issue Orders',
  PuttingIntoCirculation: 'Putting into circulation',
  Remarking: 'Remarking',
  CancelShipment: 'Cancel shipment',
  ChooseServer: 'Choose Server',
  ChooseServerDescription:
    'To continue working with the application, you need to create a server',
  OnboardingFirst: 'This app will help you with labeled products',
  OnboardingSecond: 'Just scan the DataMatrix code on the package or product',
  Skip: 'Skip',
  NotChosen: 'Not chosen',
  Send: 'Send',
  CreateServerError: 'An error occured while adding a server',
  ToServerList: 'To server list',
  ConfirmDelete: 'Do you really want to delete ',
  ConfirmDeleteButton: 'Yes, delete',
  Document: 'Document',
  DocumentData: 'Document data',
  DocumentPosition: 'Document position',
  Camera: 'Camera',
  Scanner: 'Scanner',
  ConfirmCancelScan: 'Are you sure you want to cancel the scan?',
  ConfirmCancelScanButton: 'Yes, cancel',
  Back: 'Back',
  Save: 'Save',
  AlreadyScanned: 'The code has already been scanned earlier',
  Ok: 'Ok',
  Scanned: 'Scanned',
  ScannedEmpty: 'Nothing scanned',
  Scanning: 'Scanning',
  DataNotFound: 'Data not found',
  DocumentName: 'Document name',
  DateCreated: 'Date created',
  Status: 'Status',
  ExternalID: 'External ID',
  ExternalStatus: 'External status',
  PrimaryDocumentNumber: 'Primary document number',
  PrimaryDocumentDate: 'Primary document date',
  TINOfTheBeneficiary: 'TIN of the Beneficiary',
  RecipientsName: "Recipient's name",
  SendersTIN: "Sender's TIN",
  SendersName: 'Senders name',
  OwnersTIN: "Owner's TIN",
  OwnersName: 'Owners name',
  TypeOfTurnover: 'Type of turnover',
  DateOfShipmentOfGoods: 'Date of shipment of goods',
};
