export default {
  ok: 'ОК',
  cancel: 'Отмена',
  companies: 'Компании',
  settings: 'Настройки',
  serverList: 'Список серверов',
  login: 'Вход',
  emailAddress: 'Адрес электронной почты',
  password: 'Пароль',
  loginButton: 'ВОЙТИ',
  loading: 'Загрузка',
  createServer: 'Создание сервера',
  addressServer: 'Адрес сервера',
  create: 'Создать',
  appSettings: 'Настройки приложения',
  Profile: 'Профиль',
  Warehouse: 'Склад',
  ChooseWarehouse: 'Выбор склада',
  ToCompanyList: 'К списку компаний',
  Exit: 'Выход',
  Shipment: 'Отгрузка',
  Main: 'Главная',
  LastDocuments: 'Последние документы',
  Items: 'Товары',
  MrkCodes: 'Коды маркировки',
  IssueOrders: 'Заказы на эмиссию',
  PuttingIntoCirculation: 'Ввод в оборот',
  Remarking: 'Перемаркировка',
  CancelShipment: 'Отмена отгрузки',
  ChooseServer: 'Выбор сервера',
  ChooseServerDescription:
    'Чтобы продолжить работу с приложением, необходимо создать сервер',
  OnboardingFirst: 'Это приложение поможет вам с промаркированными товарами',
  OnboardingSecond:
    'Просто отсканируйте DataMatrix код, нанесенный на упаковку или товар',
  Skip: 'Пропустить',
  NotChosen: 'Не выбрано',
  Send: 'Отправить',
  CreateServerError: 'Возникла ошибка при добавлении сервера',
  ToServerList: 'К списку серверов',
  ConfirmDelete: 'Вы действительно хотите удалить ',
  ConfirmDeleteButton: 'Да, удалить',
  Document: 'Документ',
  DocumentData: 'Данные документа',
  DocumentPosition: 'Позиции документа',
  Camera: 'Камера',
  Scanner: 'Сканер',
  ConfirmCancelScan: 'Вы уверены, что хотите отменить сканирование?',
  ConfirmCancelScanButton: 'Да, отменить',
  Back: 'Назад',
  Save: 'Сохранить',
  AlreadyScanned: 'Код уже был отсканирован ранее',
  Ok: 'Ок',
  Scanned: 'Отсканировано',
  ScannedEmpty: 'Ничего не отсканировано',
  Scanning: 'Сканирование',
  DataNotFound: 'Данные не найдены',
  DocumentName: 'Имя документа',
  DateCreated: 'Дата создания',
  Status: 'Статус',
  ExternalID: 'Внешний ID',
  ExternalStatus: 'Внешний статус',
  PrimaryDocumentNumber: 'Номер первичного документа',
  PrimaryDocumentDate: 'Дата первичного документа',
  TINOfTheBeneficiary: 'ИНН Получателя',
  RecipientsName: 'Наименование Получателя',
  SendersTIN: 'ИНН Отправителя',
  SendersName: 'Наименование Отправителя',
  OwnersTIN: 'ИНН Владельца',
  OwnersName: 'Наименование Владельца',
  TypeOfTurnover: 'Вид товарооборота',
  DateOfShipmentOfGoods: 'Дата отгрузки товара',
};
